### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by betatampw** [4sval/FModel#272]
### Game

Tower of Fantasy

### Error

```shell
[ERR] System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at CUE4Parse.UE4.Assets.Package..ctor(FArchive uasset, FArchive uexp, Lazy`1 ubulk, Lazy`1 uptnl, IFileProvider provider, TypeMappings mappings, Boolean useLazySerialization)
   at CUE4Parse.UE4.Assets.Package..ctor(FArchive uasset, FArchive uexp, FArchive ubulk, FArchive uptnl, IFileProvider provider, TypeMappings mappings, Boolean useLazySerialization)
   at CUE4Parse.FileProvider.AbstractFileProvider.LoadPackageAsync(GameFile file)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at FModel.ViewModels.CUE4ParseViewModel.Extract(String fullPath, Boolean addNewTab, Boolean bulkSave)
   at FModel.ViewModels.CUE4ParseViewModel.ExtractSelected(CancellationToken cancellationToken, IEnumerable`1 assetItems)
   at FModel.MainWindow.<>c__DisplayClass18_0.<OnAssetsListMouseDoubleClick>b__0(CancellationToken cancellationToken)
   at FModel.ViewModels.ThreadWorkerViewModel.<>c__DisplayClass20_0.<ProcessQueues>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FModel.ViewModels.ThreadWorkerViewModel.ProcessQueues()
```

### Reproduction steps

The error began to occur after updating the game to version 2 on April 25

User DOUBLE-CLICKED to extract 'Hotta/Content/AnimeToonShading/imimicry/imimicry_21/OutLine_imimicry_Hair_21_L1.uasset'
OR Save Properties

**Comment by iAmAsval** [comment]
did they change the engine version?

**Comment by betatampw** [comment]
It doesn't look like it. 
In the exe file specifies the version of Unreal Engine 4.26 (++UE4+Release-4.26-CL-0)
The error occurs only on the Chinese version of the game, the English version is also on Unreal Engine 4.26, but its files open correctly.
