### ISSUE TITLE
Questlines Notloading properly

### ISSUE THREAD

**Issue by KNProNoob** [4sval/FModel#328]
### Game

Fortnite

### Error

```shell
[ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at CUE4Parse.UE4.Assets.Exports.Material.UMaterialInstanceConstant.GetParams(CMaterialParams parameters)
[ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at CUE4Parse.UE4.Assets.Exports.Material.UMaterialInstanceConstant.GetParams(CMaterialParams parameters)
```

### Reproduction steps

1. I clicked on a quest file.

2. This is the preview image: 
![image](https://user-images.githubusercontent.com/105551979/199210048-f2d60e1e-d205-43eb-a011-09a836b6e6f7.png)

**Comment by XTigerHyperX** [comment]
Can you add the file path that produced that error?
