### ISSUE TITLE
Umaps not loading for Harvestella

### ISSUE THREAD

**Issue by narknon** [4sval/FModel#338]
### Game

Harvestella

### Error

```shell
[ERR] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CUE4Parse.UE4.Assets.Exports.Material.UMaterialInterface.GetParams(CMaterialParams2 parameters)
```

### Reproduction steps

FModel gives the above error when trying to load a .umap with the mappings file in place.  (I understand this is a brand new beta feature, just noting that it happens).  For example, Harvestella/Content/Shinsen/Maps/Levels/DGM01/DGM01_06_Area01.umap

[Harvestella.zip](https://github.com/4sval/FModel/files/10149790/Harvestella.zip)
[DGM01_06_Area01.zip](https://github.com/4sval/FModel/files/10149792/DGM01_06_Area01.zip)

**Comment by narknon** [comment]
Appears to be a static mesh issue.  Example attached.

[19:22:57 ERR] Could not read StaticMesh correctly
CUE4Parse.UE4.Exceptions.ParserException: Invalid bool value (64)
FAssetArchive Info: Harvestella/Content/Shinsen/Maps/Levels/DGR/Model/S_DGR_well.uasset Pos 4178 Length 11311
   at CUE4Parse.UE4.Assets.Exports.StaticMesh.FStaticMeshLODResources..ctor(FAssetArchive Ar) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\StaticMesh\FStaticMeshLODResources.cs:line 60
   at CUE4Parse.UE4.Assets.Exports.StaticMesh.FStaticMeshRenderData.<>c__DisplayClass7_0.<.ctor>b__0() in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\StaticMesh\FStaticMeshRenderData.cs:line 32
   at CUE4Parse.UE4.Assets.Exports.StaticMesh.FStaticMeshRenderData..ctor(FAssetArchive Ar, Boolean bCooked) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\StaticMesh\FStaticMeshRenderData.cs:line 32
   at CUE4Parse.UE4.Assets.Exports.StaticMesh.UStaticMesh.Deserialize(FAssetArchive Ar, Int64 validPos) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\StaticMesh\UStaticMesh.cs:line 53
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\AbstractUePackage.cs:line 67


[Staticmesh.zip](https://github.com/4sval/FModel/files/10149830/Staticmesh.zip)

**Comment by GMatrixGames** [comment]
In your option overrides, set
`StaticMesh.KeepMobileMinLODSettingOnDesktop`
and
`SkeletalMesh.KeepMobileMinLODSettingOnDesktop` to false

**Comment by 4sval** [comment]
or use Game_ReadyOrNot
either way, the property `ArrayIndex` of `RuntimeEntries` in your mapping file is broken and should not always be 0

on our end, we do not check the length of [`runtimeEntries`](https://github.com/FabianFG/CUE4Parse/blob/master/CUE4Parse/UE4/Assets/Exports/Material/UMaterialInterface.cs#L73) before using it
and texture names are not mapped for this game yet

once everything is fixed, it should look like this
![image](https://user-images.githubusercontent.com/26126862/205527450-d38dd915-c40b-4d29-815c-f1f4e30c61a2.png)

**Comment by narknon** [comment]
> In your option overrides, set `StaticMesh.KeepMobileMinLODSettingOnDesktop` and `SkeletalMesh.KeepMobileMinLODSettingOnDesktop` to false

Yeah, had tried these and they didn't work.  

Will do the suggestion from 4sval, thank you.

**Comment by 4sval** [comment]
[fixes](https://github.com/FabianFG/CUE4Parse/commit/20ebca59327fbd7df9d23d38722d7488395e018f)

I'm not sure if the RuntimeEntries ArrayIndex issue is related to us or the mapping generator. It could be fixed on our end but it was working fine for the 6-10 different games this new fmodel has been stress tested on. So idk

**Comment by narknon** [comment]
Thank you.  Here's another one that I've generated using Shade's dumper if you want to see if the issue exists there as well.

[Grounded.zip](https://github.com/4sval/FModel/files/10150066/Grounded.zip)

**Comment by narknon** [comment]
Hmm, an issue seems to persist, though the errors are different now.

```[20:57:09 ERR] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CUE4Parse.UE4.Assets.Exports.Material.UMaterialInterface.GetParams(CMaterialParams2 parameters) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\Material\UMaterialInterface.cs:line 82
   at CUE4Parse.UE4.Assets.Exports.Material.UMaterial.GetParams(CMaterialParams2 parameters) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\Material\UMaterial.cs:line 223
   at CUE4Parse.UE4.Assets.Exports.Material.UMaterialInstanceConstant.GetParams(CMaterialParams2 parameters) in S:\Github Projects\FModel\CUE4Parse\CUE4Parse\UE4\Assets\Exports\Material\UMaterialInstanceConstant.cs:line 250
   at FModel.Views.Snooper.Material.SwapMaterial(UMaterialInterface unrealMaterial) in S:\Github Projects\FModel\FModel\Views\Snooper\Material.cs:line 61
   at FModel.Views.Snooper.Material..ctor(UMaterialInterface unrealMaterial) in S:\Github Projects\FModel\FModel\Views\Snooper\Material.cs:line 55
   at FModel.Views.Snooper.Model..ctor(UObject export, ResolvedObject[] materials, FPackageIndex skeleton, CBaseMeshLod lod, CMeshVertex[] vertices, Transform transform) in S:\Github Projects\FModel\FModel\Views\Snooper\Model.cs:line 102
   at FModel.Views.Snooper.Model..ctor(UStaticMesh export, CStaticMesh staticMesh, Transform transform) in S:\Github Projects\FModel\FModel\Views\Snooper\Model.cs:line 74
   at FModel.Views.Snooper.Model..ctor(UStaticMesh export, CStaticMesh staticMesh) in S:\Github Projects\FModel\FModel\Views\Snooper\Model.cs:line 73
   at FModel.Views.Snooper.Renderer.LoadStaticMesh(UStaticMesh original) in S:\Github Projects\FModel\FModel\Views\Snooper\Renderer.cs:line 160
   at FModel.Views.Snooper.Renderer.Load(CancellationToken cancellationToken, UObject export) in S:\Github Projects\FModel\FModel\Views\Snooper\Renderer.cs:line 54
   at FModel.Views.Snooper.Snooper.TryLoadExport(CancellationToken cancellationToken, UObject export) in S:\Github Projects\FModel\FModel\Views\Snooper\Snooper.cs:line 39
   at FModel.ViewModels.CUE4ParseViewModel.CheckExport(CancellationToken cancellationToken, UObject export) in S:\Github Projects\FModel\FModel\ViewModels\CUE4ParseViewModel.cs:line 799
   at FModel.ViewModels.CUE4ParseViewModel.Extract(CancellationToken cancellationToken, String fullPath, Boolean addNewTab, Boolean bulkSave) in S:\Github Projects\FModel\FModel\ViewModels\CUE4ParseViewModel.cs:line 584
   at FModel.ViewModels.CUE4ParseViewModel.ExtractSelected(CancellationToken cancellationToken, IEnumerable`1 assetItems) in S:\Github Projects\FModel\FModel\ViewModels\CUE4ParseViewModel.cs:line 547
   at FModel.MainWindow.<>c__DisplayClass18_0.<OnAssetsListMouseDoubleClick>b__0(CancellationToken cancellationToken) in S:\Github Projects\FModel\FModel\MainWindow.xaml.cs:line 181
   at FModel.ViewModels.ThreadWorkerViewModel.<>c__DisplayClass24_0.<ProcessQueues>b__0() in S:\Github Projects\FModel\FModel\ViewModels\ThreadWorkerViewModel.cs:line 87
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FModel.ViewModels.ThreadWorkerViewModel.ProcessQueues() in S:\Github Projects\FModel\FModel\ViewModels\ThreadWorkerViewModel.cs:line 87
```

**Comment by 4sval** [comment]
https://github.com/FabianFG/CUE4Parse/blob/master/CUE4Parse/UE4/Assets/Objects/FStructFallback.cs#L54

get rid of maxIndex and simply convert everything inside the typed list to a generic list

**Comment by 4sval** [comment]
> https://github.com/FabianFG/CUE4Parse/blob/master/CUE4Parse/UE4/Assets/Objects/FStructFallback.cs#L54
> 
> get rid of maxIndex and simply convert everything inside the typed list to a generic list
> 
> aka
> 
> populate `obj` by index from `collected` without using `maxIndex` as the length of `obj`

**Comment by 4sval** [comment]
the property ArrayIndex is the problem, again

**Comment by 4sval** [comment]
I reverted [this change](https://github.com/FabianFG/CUE4Parse/commit/20ebca59327fbd7df9d23d38722d7488395e018f#diff-56c916ccf0d7fb12bca0e6f70d80b6ff19eb62bd92b2a699ec0b346aea60f671) because this was not part of the problem
the root issue is either the game exe, or the mapping

ArrayIndex of RuntimeEntries should not be zero for every entry
it's been tested on games that use and do not use mappings and that's just how it works
if ArrayIndex is zero every time, TryGetAllValues will return a list of existing entries and so there will be no way to tell what type of entry it is

**Comment by narknon** [comment]
What do you generally use to generate mappings?

**Comment by GMatrixGames** [comment]
https://github.com/OutTheShade/UnrealMappingsDumper

**Comment by narknon** [comment]
That's what I've used as well.  FModel seems to have issues with static meshes in a number of games since the update to 4.4 though.  Several games have no issue on older versions, CCFF7R for example works on 4.3.2.1 with one edit to matinstconstant, but not on 4.4 with the same edit.

**Comment by 4sval** [comment]
a full fix is coming

they have no issue with older versions because since 4.4 we fully read materials until we have enough info for our generic shader

**Comment by narknon** [comment]
Great, thank you for your work.
