### ISSUE TITLE
Unable to preview models

### ISSUE THREAD

**Issue by DeStilleGast** [4sval/FModel#345]
### Game

Dead by daylight

### Error

```shell
=== [Error in FModel itself] ===
[ERR] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()

=== [ log file ] ===
2022-12-12 22:07:42 [FModel] [INF] User DOUBLE-CLICKED to extract 'DeadByDaylight/Content/Characters/Campers/Meg/Models/Torsos/MT_Torso01_REF.uasset'
2022-12-12 22:07:42 [FModel] [ERR] Could not read SkeletalMesh correctly
CUE4Parse.UE4.Exceptions.ParserException: Invalid bool value (47)
FAssetArchive Info: DeadByDaylight/Content/Characters/Campers/Meg/Models/Torsos/MT_Torso01_REF.uexp Pos 11106 Length 1019448
   at CUE4Parse.UE4.Assets.Exports.SkeletalMesh.FStaticLODModel.SerializeRenderItem(FAssetArchive Ar, Boolean bHasVertexColors, Byte numVertexColorChannels)
   at CUE4Parse.UE4.Assets.Exports.SkeletalMesh.USkeletalMesh.Deserialize(FAssetArchive Ar, Int64 validPos)
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize)
2022-12-12 22:07:42 [FModel] [ERR] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at FModel.Views.Snooper.Model..ctor(USkeletalMesh export, CSkeletalMesh skeletalMesh)
   at FModel.Views.Snooper.Renderer.LoadSkeletalMesh(USkeletalMesh original)
   at FModel.Views.Snooper.Renderer.Load(CancellationToken cancellationToken, UObject export)
   at FModel.Views.Snooper.Snooper.TryLoadExport(CancellationToken cancellationToken, UObject export)
   at FModel.ViewModels.CUE4ParseViewModel.CheckExport(CancellationToken cancellationToken, UObject export)
   at FModel.ViewModels.CUE4ParseViewModel.Extract(CancellationToken cancellationToken, String fullPath, Boolean addNewTab, Boolean bulkSave)
   at FModel.ViewModels.CUE4ParseViewModel.ExtractSelected(CancellationToken cancellationToken, IEnumerable`1 assetItems)
   at FModel.MainWindow.<>c__DisplayClass18_0.<OnAssetsListMouseDoubleClick>b__0(CancellationToken cancellationToken)
   at FModel.ViewModels.ThreadWorkerViewModel.<>c__DisplayClass24_0.<ProcessQueues>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FModel.ViewModels.ThreadWorkerViewModel.ProcessQueues()
```

### Reproduction steps

1. Open DeadByDaylight in FModel
2. Locate character model part
3. Attempt to open it.

**Comment by 4sval** [comment]
https://github.com/4sval/FModel/issues/338#issuecomment-1336579576
