### ISSUE TITLE
Cant launch Fmodel

### ISSUE THREAD

**Issue by phantom54** [4sval/FModel#365]
### Game

no game. fmodel just doesnt start

### Error

```shell
2023-03-05 14:26:40 [FModel] [INF] Version 4.4.1.1
2023-03-05 14:26:40 [FModel] [INF] Windows 11 Pro (64-bit)
2023-03-05 14:26:40 [FModel] [INF] .NET 6.0.14
2023-03-05 14:26:40 [FModel] [INF] Culture ru-RU
2023-03-05 14:26:40 [FModel] [INF] "C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat" found in drive "C:\"
2023-03-05 14:26:40 [FModel] [WRN] Could not find Fortnite in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find Pewee in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find Rosemallow in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find Catnip in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find AzaleaAlpha in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find WorldExplorersLive in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find Newt in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find shoebill in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find Snoek in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find a99769d95d8f400baad1f67ab5dfe508 in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find Nebula in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find 711c5e95dc094ca58e5f16bd48e751d6 in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] Could not find 9361c8c6d2f34b42b5f2f61093eedf48 in LauncherInstalled.dat
2023-03-05 14:26:40 [FModel] [WRN] "ProgramData\Riot Games\RiotClientInstalls.json" not found in any drives
2023-03-05 14:26:40 [FModel] [WRN] Could not find VALORANT in RiotClientInstalls.json
2023-03-05 14:26:40 [FModel] [INF] "C:\Users\YourDevil54\AppData\Roaming\.minecraft\launcher_settings.json" found in "C:\Users\YourDevil54\AppData\Roaming"
2023-03-05 14:26:40 [FModel] [ERR] System.Windows.Markup.XamlParseException: Вызов конструктора для типа "FModel.MainWindow", удовлетворяющего указанным ограничениям привязки, привел к выдаче исключения.
 ---> System.TypeInitializationException: The type initializer for 'FModel.Services.ApplicationService' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SteamDetection' threw an exception.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Games\SteamApps'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at FModel.ViewModels.GameSelectorViewModel.SteamDetection.<>c.<GetSteamApps>b__3_1(String appMetaDataPath)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at FModel.ViewModels.GameSelectorViewModel.SteamDetection.GetSteamApps(IEnumerable`1 steamLibs)
   at FModel.ViewModels.GameSelectorViewModel.SteamDetection..cctor()
   --- End of inner exception stack trace ---
   at FModel.ViewModels.GameSelectorViewModel.SteamDetection.GetSteamGameById(Int32 id)
   at FModel.ViewModels.GameSelectorViewModel.GetSteamGame(Int32 id, String pakDirectory)
   at FModel.ViewModels.GameSelectorViewModel.EnumerateDetectedGames()+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1.CreateCopy(IEnumerable`1 collection, String paramName)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at FModel.ViewModels.GameSelectorViewModel..ctor(String gameDirectory)
   at FModel.ViewModels.ApplicationViewModel.AvoidEmptyGameDirectoryAndSetEGame(Boolean bAlreadyLaunched)
   at FModel.ViewModels.ApplicationViewModel..ctor()
   at FModel.Services.ApplicationService..cctor()
   --- End of inner exception stack trace ---
   at FModel.Services.ApplicationService.get_ApplicationView()
   at FModel.MainWindow.get__applicationView()
   at FModel.MainWindow..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Reproduction steps

https://i.imgur.com/RGTZIZ1.jpeg
and i can see it in taskmanager - i have to kill it, or it wont close after the error

**Comment by phantom54** [comment]
nevermind
---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Games\SteamApps'.
i didnt had steamapps folder here so i removed library disk (E:\Games) in steam settings and it fixed the problem
