### ISSUE TITLE
Fmodel is crashing on preview and extracting any assets

### ISSUE THREAD

**Issue by Organizer21** [4sval/FModel#414]
### Game

Palia

### Error

```shell
[INF] 54 virtual paths loaded
[INF] 153999 localized resources loaded for 'English'
[ERR] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CUE4Parse.UE4.Readers.FByteArchive.Read()


---- from log file ----

2023-08-16 16:03:36 [FModel] [INF] Version 4.4.3.2
2023-08-16 16:03:36 [FModel] [INF] Windows 11 Pro (64-bit)
2023-08-16 16:03:36 [FModel] [INF] .NET 6.0.9
2023-08-16 16:03:36 [FModel] [INF] Culture en-GB
2023-08-16 16:03:54 [FModel] [ERR] System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'FModel.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'FModel.Services.ApplicationService' threw an exception.
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider..ctor(String directory, SearchOption searchOption, Boolean isCaseInsensitive, VersionContainer versions)
   at FModel.ViewModels.CUE4ParseViewModel..ctor(String gameDirectory)
   at FModel.ViewModels.ApplicationViewModel..ctor()
   at FModel.Services.ApplicationService..cctor()
   --- End of inner exception stack trace ---
   at FModel.Services.ApplicationService.get_ApplicationView()
   at FModel.MainWindow.get__applicationView()
   at FModel.MainWindow..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Reproduction steps

It's a new F2P game so the client is free, I don't think the paks are protected. But not able to preview any models or images from e.g. pakchunk0-windowsclient.pak (4.39gb) | Just browsing that pak, going to Palia > Content > UI > Icons and double clicking any of the .uassets as to crash Fmodel without any error message (did the anyjam myself, one of the 2-3 first, some might give an error see error log abouve index outside bound of array.

Hope this is enough, no expert on this and it seems no other tools so far either I have tried manage to preview or convert any assets to e.g. png with this new game. Not sure if it's something they have done, if it's a newer UE build not yet support or why that is, have managed to extract from other games in the past with the same tools.

**Comment by 4sval** [comment]
use the correct ue version
